name: Build on Windows

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc
      
      - name: Build Windows
        run: cargo build --release --target x86_64-pc-windows-msvc
        
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pixie-installer-windows
          path: target/x86_64-pc-windows-msvc/release/pixie-installer.exe
